### ISSUE TITLE
multiple jquery installations

### ISSUE THREAD

**Issue by aroscoe** [dcramer/django-debug-toolbar#1]
I was having lots of issues with jQuery and I just realized that it was because debug-toolbar is adding their own version of the library. 

It was somehow resetting my plugins when your jQuery library was pulled. I see that you are running it in no conflict, but unfortunately that is doing me no good. I was able to comment out the inclusion of your library (v 1.2.6) and just let debug-toolbar use mine (v 1.3.2) and everything worked fine.

It would be nice if debug-toolbar could recognize if jQuery was already installed and then just skip it's own installation.

**Comment by fotinakis** [comment]
I've fixed this here: http://github.com/fotinakis/django-debug-toolbar/commit/b50c33891f4652cde675d8c9920c281979f8bcd3

I was also having this issue. What happens is the jQuery object is overwritten by your included jquery.js and then any custom functions that you have defined (ie. plugins you have installed) no longer exist on the jQuery object at page load.

**Comment by aroscoe** [comment]
Nice. This is exactly what I was talking about. Thank you.

**Comment by dcramer** [comment]
Just merged the patch into main

**Comment by aroscoe** [comment]
Thanks.

**Comment by streeter** [comment]
So I'm having issues with multiple jQuery installs. I've got a library that is using the jQuery object directly (not the $ alias) which is then using the DjDT provided library. I noticed that the above commit was changed so as to include the js directly into the page inline instead of as a separate `<script src="..">` tag. However, the check to not include the DjDT jQuery library is no longer there and I'm getting my library clobbered.

Here's the output from the web inspector console:

```
> $.fn.jquery
   "1.6.2"
> jQuery.fn.jquery
   "1.4.1"
>
```

A thought to fix this is to provide a DjDT setting that causes it to skip including it's own jQuery library, thus using the one already provided on the page. I'm willing to provide the pull request. Any other ideas of how to fix this?
