### ISSUE TITLE
Profiling and debugging a production site

### ISSUE THREAD

**Issue by jarshwah** [dcramer/django-debug-toolbar#20]
Currently, the way DDT works is by configuring the deployment in DEBUG mode (DEBUG = True), and by specifying the IP addresses of those that should have access. This all works quite nicely in a development environment, but it makes it extremely difficult to profile a live site.

Has there been discussion of possible alternative methods for enabling the toolbar on a live site? Perhaps by using permissions, or simply the user.is_admin()? If developers are always able to access debug information, chances are higher that performance will be monitored via developers dogfooding their own sites.

I'd be quite interested in developing a different method for enabling the toolbar. I'm just wondering if I'm covering old ground, and if there are significant reasons that things work the way they do?

**Comment by streeter** [comment]
Check out the setting for `SHOW_TOOLBAR_CALLBACK`. It lets you pass in an arbitrary function that can look at the `request` and decide whether to show the toolbar at [this line](https://github.com/dcramer/django-debug-toolbar/blob/master/debug_toolbar/middleware.py#L49). Otherwise, the toolbar falls back to [this line](https://github.com/dcramer/django-debug-toolbar/blob/master/debug_toolbar/middleware.py#L59).

**Comment by jarshwah** [comment]
Hah, so there is. And pretty much the idea I had running in my head. Thanks for pointing this out.
